services:
  db:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_USER: redsistencia
      POSTGRES_PASSWORD: red12345
      POSTGRES_DB: postgres
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: